language: python

python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'

script:
- python test.py

deploy:
  provider: pypi
  user: scisco
  password:
    secure: UrYVQs2TNpuIPP0nt7ArStrnW2FlZPxB2LEYHY2grGx1KRCPgTzO6pY7tNtTX5nnLev+TGoXJXqMGB9QRwKH7GuCRBhl0qad6AiskyxAcUFfZ0We7GR3K0Fo0nxsdmuzwnVAoVoJZUPM9IYdrs+OroxowDZic3CskgFiw/g0jH7xxeYwY+y880uNjgnsY7hwMui54R/mSKC6EGTjfsZa3UzxQOqnYS2rCoSWLeb9CZ7A+fcWOa3iDTBFyEgSRM3/yHUWdvxDAsUI5XfJuOmohQf4QLJvv0TtQ6MuCAepG1Oy5ve+XJzdqdhOkqRXgBvb+VluyuJ6u3qcB8UMw7jRcbgcYS8YuMgSdUW9yGTAZ0gfFlHdi57IAciloW4O7DxALRHXijYfz0o9Xa+NE1uY7kJvu7d7OYPepHTfKKKtM8axS9cILJ1KBHyIao28pLitV+QdEFIQJ1ioPh+ejCKMa9iQLId0v0S+elS5MP5pfulF8TbbsMbI2J4+8Ncab0Q8yeCENvhnVWnGqgM6s/IZA3reQt+zUDks/FlPuvFuUWHqYA7744PEJlGuFl85iPFtNEr7NODycvgpxUbSHUby6BkGDfW2GKgjAPWypXoQGep/T1Xybt7gcbfv47SCPNodrgbwfvBI5i/3+nszmoBDsr/w9iEoElLWYPnQ4B1TF24=
  on:
    repo: scisco/boolean
    branch: master
